### ISSUE TITLE
Refactor sources after Java to Kotlin conversion

### ISSUE THREAD

**Issue by dzikoysk** [panda-lang/hub#534]

**Comment by supergrecko** [comment]
Hi, I wouldn't mind looking into this, could you elaborate on what has to be done?

Judging from the title I assume we want a more idiomatic kotlin approach to the codebase.

**Comment by dzikoysk** [comment]
Yeah, the sources (`hub-backend`) are pretty dirty after conversion from Java. There is a lot of unnecessary operations which can be replaced with a standard Kotlin features. The task is to just review these classes and refactor them, it does not require much of knowledge about the project and its logic - it is why it should be quite achievable for newcomers :)

**Comment by supergrecko** [comment]
Okay cool, I'll have a look at it later today and submit a patch for review.

**Comment by dzikoysk** [comment]
I'm not familiar with a standard kotlin based web stack, but I've heard that ktlint is a pretty common solution here, so yeah... it might be a good idea to add it :)

**Comment by dzikoysk** [comment]
Related issue: #537

**Comment by dzikoysk** [comment]
#638
